# Generated by Django 4.2.4 on 2024-06-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actividades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Donaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("info", models.TextField()),
                ("info_impacto", models.TextField()),
                ("historial", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Historias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("testimonios", models.TextField()),
                ("enlaces", models.URLField(blank=True, null=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="historias/"),
                ),
                ("video", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="noticias/"),
                ),
                ("video", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("mision", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="nosotros/"),
                ),
                ("video", models.URLField(blank=True, null=True)),
                ("testimonios", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Programas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("articulos", models.TextField()),
                ("enlaces", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
