# Generated by Django 4.2.4 on 2024-06-10 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actividades",
            options={"verbose_name": "Actividad", "verbose_name_plural": "Actividades"},
        ),
        migrations.AlterModelOptions(
            name="donaciones",
            options={"verbose_name": "Donación", "verbose_name_plural": "Donaciones"},
        ),
        migrations.AlterModelOptions(
            name="historias",
            options={"verbose_name": "Historias", "verbose_name_plural": "Historiales"},
        ),
        migrations.AlterModelOptions(
            name="inicio",
            options={"verbose_name": "Inicio", "verbose_name_plural": "Inicio"},
        ),
        migrations.AlterModelOptions(
            name="nosotros",
            options={"verbose_name": "Noticia", "verbose_name_plural": "Noticias"},
        ),
        migrations.AlterModelOptions(
            name="programas",
            options={"verbose_name": "Programa", "verbose_name_plural": "Programas"},
        ),
        migrations.AlterModelOptions(
            name="seccion",
            options={"verbose_name": "Seccion", "verbose_name_plural": "Secciones"},
        ),
    ]
