# Generated by Django 4.2.4 on 2024-06-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_actividades_options_alter_donaciones_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inicio",
            name="ofertas",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="seccion",
            name="icono",
            field=models.ImageField(blank=True, upload_to="seccion/"),
        ),
    ]
