# Generated by Django 4.2.4 on 2024-06-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_inicio_ofertas_seccion_icono"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("articulos", models.TextField()),
                ("enlaces", models.URLField(blank=True, null=True)),
                ("icono", models.ImageField(blank=True, upload_to="articulo/")),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
            },
        ),
        migrations.DeleteModel(
            name="Seccion",
        ),
        migrations.AlterModelOptions(
            name="nosotros",
            options={"verbose_name": "Nosotros", "verbose_name_plural": "Nosotros"},
        ),
    ]
