# Generated by Django 4.2.4 on 2024-06-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_articulos_delete_seccion_alter_nosotros_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonacionesCBU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=255)),
                ("sucursal", models.CharField(max_length=200)),
                ("cbu", models.BigIntegerField()),
                ("alias", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "DonaciónCBU",
                "verbose_name_plural": "DonacionesCBU",
            },
        ),
        migrations.RenameField(
            model_name="articulos",
            old_name="enlaces",
            new_name="enlaces_formulario",
        ),
        migrations.RemoveField(
            model_name="articulos",
            name="icono",
        ),
        migrations.RemoveField(
            model_name="donaciones",
            name="info",
        ),
        migrations.RemoveField(
            model_name="nosotros",
            name="testimonios",
        ),
    ]
