# Generated by Django 4.2.4 on 2024-06-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_donacionescbu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donacionescbu",
            name="cbu",
            field=models.TextField(),
        ),
    ]
