# Generated by Django 4.2.4 on 2024-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_donacionescbu_cbu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donacionescbu",
            name="cbu",
            field=models.CharField(max_length=250),
        ),
    ]
