# Generated by Django 4.2.4 on 2024-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_actividades_descripcion_alter_actividades_info_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historias",
            options={"verbose_name": "Historias", "verbose_name_plural": "Historias"},
        ),
        migrations.AddField(
            model_name="articulos",
            name="imagenes",
            field=models.ImageField(blank=True, upload_to="articulo/"),
        ),
    ]
