# Generated by Django 4.2.4 on 2024-06-22 15:05

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_historias_options_articulos_imagenes"),
    ]

    operations = [
        migrations.AddField(
            model_name="donaciones",
            name="donar",
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
